### ISSUE TITLE
bd_warehouse installs with no errors, import gives no errors, but test fails

### ISSUE THREAD

**Issue by haunma** [gumyr/bd_warehouse#24]
Following the installation instructions, I used pip to install bd_warehouse from github.  Then, following the suggestion to test it, I tried
```
from bd_warehouse import *
print(Solid.make_box(1,2,3).show_topology(limit_class="Face"))
```
The import does not complain, but the test line gives the error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Solid' is not defined
```
It appears that no classes defined in bd_warehouse are actually available.

This was installed in a python 3.12.3 venv on Linux, with a working build123d installation already installed.

**Comment by haunma** [comment]
Ah, so it looks like the post-installation test and most of the examples in the documentation no longer work due to changes to the structure of the library, changes to parameter names, and so on.

Leaving this issue here as a "documentation is wrong" catch-all.

**Comment by gumyr** [comment]
Thanks for pointing this problem out.  The installation test was a copy/paste from build123d and much of the content comes from cq_warehouse which (incorrectly) uses camelCase.  All of this should be fixed now but if you find anything else please raise another Issue.
