### ISSUE TITLE
Suggestion: Use normal `import build123d as bd` in this library to support better type checking

### ISSUE THREAD

**Issue by KilowattSynthesis** [gumyr/bd_warehouse#44]
I know that the standard for creating CAD drawings is to use `from build123d import *` - I'm totally onboard with that. 

Can I suggest that it would be better if, in this **library** though, you used the normal `import build123d as bd`. The benefit of this is high reliablity in the releases/pushes of this awesome library! The bug fixed in my PR #43 would have been caught by a standard linter if not for the `import *`. 

Curious to hear your thoughts! I'd be very open to helping facilitate this move if you're interested.

**Comment by gumyr** [comment]
Thanks for the input.  This use of the [glob import](https://build123d.readthedocs.io/en/latest/tips.html#isnt-from-build123d-import-bad-practice) is discussed in the build123d docs. Having a proper CI system with tests is how I'd like to solve this problem - see issue #42.

**Comment by KilowattSynthesis** [comment]
I read that blurp months ago, and I read it again just now. I'll highlight a few parts of it that seem relevant in this case, hence why I opened the issue:

> Glob imports like from build123d import * are generally frowned upon when writing software

bd_warehouse is software (a library); not a single CAD design.

> If your goal is to integrate build123d into a larger piece of software, which many people work on, or where long-term maintainability is a priority, using this approach [non-glob imports] is definitely a good idea!

This certainly seems like a library, which many people (or at least a few) work on. I assume long-term maintainability is a priority, as we just discussed a CI pipeline in #42 (which would benefit hugely from non-glob imports). 

Thoughts?

**Comment by gumyr** [comment]
Adding static checking would be great but I'm simply too busy to do this with bd_warehouse - I'm in the middle of doing this for build123d itself.

**Comment by KilowattSynthesis** [comment]
Would you approve me implementing this fix, as described in the issue, as an important first step?

**Comment by gumyr** [comment]
Not at this point.  If you'd like to help adding some tests would be appreciated.
