### ISSUE TITLE
AttributeError: property 'size' of 'MetricTrapezoidalThread' object has no setter

### ISSUE THREAD

**Issue by lincolnjohnson** [gumyr/bd_warehouse#6]
Using any variation of the following code results in the AttributeError in the title.

`test = MetricTrapezoidalThread(size="32x3", length=50.0, external=True)`

The flange and pipe examples shown in the docs work fine. I can provide additional information if it would be helpful.

**Comment by gumyr** [comment]
Thanks for pointing this out.  I need to run the bd_warehouse tests with every build123d change...
